language: go

sudo: false

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

install:
  - cd logAgent && go build && cd -
  - cd logTransfer && go build && cd -
  - cd logManager && go build && cd -

script:
  - cd logAgent && go test -v ./... && cd -
  - cd logTransfer && go test -v ./... && cd -
  - cd logManager && go test -v ./... && cd -
